# basic options
title: Tidewater Community College Cybersecurity Club (TC4)
author: tcccybersecclub
email: webmaster@tc4.space
description: This is the homepage for TC4

#build settings
theme: jekyll-theme-hacker
