# basic options
title: TCC Cybersecurity Club (TC4)
author: tcccybersecclub
email: webmaster@tc4.space
description: An Official Tidewater Community College Student Organization

#build settings
theme: jekyll-theme-hacker
